### ISSUE TITLE
Turning the monitor off and on resets the refresh rate

### ISSUE THREAD

**Issue by Faugus** [labwc/labwc#1345]
If I set the resolution/refresh rate with `kanshi` or `wlr-randr` to 2560x1440@144, every time I turn my monitor off and on it resets the resolution/refresh rate to 2560x1440@60.
Also, `waybar` crashes, but it also happens with hyprland.

**Comment by johanmalm** [comment]
Thanks for reporting. Will look into it.

**Comment by johanmalm** [comment]
There is some output related fixes in wlroots `0.17.1`.
Any chance of testing with that?

https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/0.17.1

**Comment by Faugus** [comment]
I don't get it. Labwc uses a package called `wlroots0.16` on Arch. And the updated one is called `wlroots`.
How do I make Labwc use the updated one?
```
[faugus@archlinux ~]$ sudo pacman -Q | grep wlroots
wlroots 0.17.0-1
wlroots0.16 0.16.2-2
```

**Comment by ahesford** [comment]
Is this with amdgpu, by chance? May be related to https://github.com/labwc/labwc/issues/1281.

**Comment by Faugus** [comment]
Yes it is.

**Comment by ahesford** [comment]
I have a suspicion that this is not a labwc bug; cf. [my analysis](https://github.com/labwc/labwc/issues/1281#issuecomment-1872335403) of the issue.

**Comment by ahesford** [comment]
If you're using kanshi, this issue should be fixed by the recently released version 1.5.1.

**Comment by Faugus** [comment]
True. I just tried and it's working now with Kanshi. Waybar still crashes when I turn off my monitor, but that's another problem.
