### ISSUE TITLE
Problem with title-bar translucency

### ISSUE THREAD

**Issue by tsujan** [labwc/labwc#1684]
I explain the issue with an example:

When I use `window.active.title.bg.color: #3a3a3b 95`, I apparently have a nice, translucent title-bar:

![95](https://github.com/labwc/labwc/assets/981076/8c820513-8bb3-44a8-ac4d-23de67542cd9)

However, there is a problem, which is made visible when I decrease the opacity, like `window.active.title.bg.color: #3a3a3b 70`:

![70](https://github.com/labwc/labwc/assets/981076/85e4c17b-a97a-4899-9e32-0e993b92656c)

As the screenshot shows, the opacity of the the left and right corners is different from that of the title-bar. It should be related to how the rounded corners are drawn; it doesn't exist in maximized windows.

I use 0.7.1 plus the patch for shadows.

P.S. There's also another, minor issue with title-bar translucency, which I may explain elsewhere.

**Comment by ahesford** [comment]
Does the problem go away for non-maximized windows if you set the corner radius to 0?

**Comment by tsujan** [comment]
No, it doesn't, contrary to what I expected: The issue is still visible with `<cornerRadius>0</cornerRadius>` and `window.active.title.bg.color: #3a3a3b 70`.

**Comment by Consolatis** [comment]
The corners are drawn by cairo, the titlebar and other button backgrounds are drawn by wlroots via the scene graph API. Maybe this is an issue of pre-multipled vs not premultipled rgb values.

**Comment by tsujan** [comment]
> Maybe this is an issue of pre-multipled vs non pre-multipled RGB values

@Consolatis, does the following observation confirm that?

If I change the color to back, everything is OK. I tested with `window.active.title.bg.color: #000000 70` and `window.active.title.bg.color: #000000 50` to make sure.

This may also be related to the second issue that I found (but didn't explain above): With translucency, the title-bar color isn't exactly what it should be. To make the translucent title-bar match my Qt windows, I used `#3a3a3b`, while the color of my Qt windows was `#3d3d3e` — in other words, I had to decrease the color value of the title-bar from 62 to 59 to make it match the window.

**Comment by tsujan** [comment]
BTW, I encountered the second issue in Wayfire too (the necessity of decreasing the color value with translucency).

**Comment by Consolatis** [comment]
>  in other words, I had to decrease the color value of the title-bar from 62 to 59 to make it match the window.

That sounds more like a rounding issue (alpha is usually between 0-255 and we are using percent value e.g. 0-100).
I've added this issue to the 0.7.2 milestone but don't currently have the time to investigate this in more detail.

**Comment by tsujan** [comment]
> The first variant sounds easier to implement and maintain....

Isn't a non-premultiplied value more intuitive, as far as ordinary users are concerned?

**Comment by Consolatis** [comment]
> > The first variant sounds easier to implement and maintain....
> 
> Isn't a non-premultiplied value more intuitive, as far as ordinary users are concerned?

It is just labwc internal, externally we'd still support unmultiplied colors.
Does this fix the issue?
```diff
diff --git a/src/common/graphic-helpers.c b/src/common/graphic-helpers.c
index 460b6760..6ec503c1 100644
--- a/src/common/graphic-helpers.c
+++ b/src/common/graphic-helpers.c
@@ -85,7 +85,11 @@ draw_cairo_border(cairo_t *cairo, struct wlr_fbox fbox, double line_width)
 void
 set_cairo_color(cairo_t *cairo, const float *c)
 {
-	cairo_set_source_rgba(cairo, c[0], c[1], c[2], c[3]);
+	/*
+	 * We are dealing with pre-multiplied colors
+	 * but cairo expects unmultiplied colors here
+	 */
+	cairo_set_source_rgba(cairo, c[0] / c[3], c[1] / c[3], c[2] / c[3], c[3]);
 }
 
 struct surface_context
diff --git a/src/theme.c b/src/theme.c
index 8ad93384..0ecf28cf 100644
--- a/src/theme.c
+++ b/src/theme.c
@@ -406,6 +406,10 @@ parse_hexstr(const char *hex, float *rgba)
 	rgba[2] = (hex_to_dec(hex[5]) * 16 + hex_to_dec(hex[6])) / 255.0;
 	if (strlen(hex) > 7) {
 		rgba[3] = atoi(hex + 7) / 100.0;
+		/* Pre-multiply everything as expected by wlr_scene */
+		rgba[0] *= rgba[3];
+		rgba[1] *= rgba[3];
+		rgba[2] *= rgba[3];
 	} else {
 		rgba[3] = 1.0;
 	}
```

**Comment by tokyo4j** [comment]
> adjust `parse_hexstr()` in `theme.c` to pre-multiply and patch `set_cairo_color()` to undo it before calling `cairo_set_source_rgba()`

I really appreciate if this patch is made, as I want to make the color and opacity of overlay configurable in a future PR.

BTW, another problem with translucent titlebar is, after #1631, another translucent layer is drawn behind the title text.

**Comment by tsujan** [comment]
> after https://github.com/labwc/labwc/pull/1631, another translucent layer is drawn behind the title text.

I think this was the cause of the difference between what @stefonarch and I saw: In his case, the background of the text was also different from the rest of the translucent title-bar. He uses git LabWC.

**Comment by Consolatis** [comment]
Well, not sure how to solve that.. Thoughts @jlindgren90 @ahesford ?

**Comment by tsujan** [comment]
> Does this fix the issue?

Yes, it does, when applied to 0.7.1. A screenshot with `window.active.title.bg.color: #3a3a3b 70`:

![patched](https://github.com/labwc/labwc/assets/981076/942dd1c4-a501-44b8-9291-fa7fa7aa8a71)

**Comment by ahesford** [comment]
I wonder if font rendering still does the right thing with respect to sub-pixel rendering if the background color is set to match the title bar but its opacity approaches zero. I see a few options:
1. If we can set the background color with negligible opacity, that should be sufficient.
2. We could split the title bar as suggested by @Consolatis.
3. Maybe we can force-disable sub-pixel rendering for the title if the title bar has anything other than full opacity.

**Comment by tsujan** [comment]
Oh, perhaps needless to say, the second issue is also fixed by @Consolatis's patch :) Thanks a lot!

**Comment by jlindgren90** [comment]
> I wonder if font rendering still does the right thing with respect to sub-pixel rendering if the background color is set to match the title bar but its opacity approaches zero

I would guess that it will still have the same problem it had when the background was fully transparent. The RGB values it produced exceeded the alpha value (which is undefined for pre-multiplied alpha).

It should work okay if we render the text on top of an opaque buffer and then apply transparency to the whole buffer afterward. The subpixel effect will be muted a bit as the titlebar becomes more transparent, but that's unavoidable, I think.

**Comment by jlindgren90** [comment]
A question - are we going for the opacity of the title text to match the overall titlebar? Or is the intent to have fully opaque text on an otherwise semi-transparent titlebar?

**Comment by Consolatis** [comment]
> A question - are we going for the opacity of the title text to match the overall titlebar? Or is the intent to have fully opaque text on an otherwise semi-transparent titlebar?

That is a good question.
My intuition would be to go for fully opaque text on semi-transparent background because otherwise it will get hard to read.

**Comment by jlindgren90** [comment]
Okay - I think in that case we basically have no choice but to disable subpixel rendering (because the final background color is dependent on the surface below, and subpixel rendering requires knowing the background color as it's basically doing its own alpha blending internally).

**Comment by ahesford** [comment]
I'd rather see opaque text as well, but my preference can be swayed by the relative complexity of implementing the two alternatives.

**Comment by jlindgren90** [comment]
It's probably less of a tear-up of the labwc source to do it that way, because we can continue using a separate overlaid buffer.

I would prefer to keep subpixel rendering for the fully opaque case - so it's probably just an issue of checking if the alpha is < 1, and rendering on top of transparency (with subpixel rendering disabled) in that case.

**Comment by Consolatis** [comment]
> Oh, perhaps needless to say, the second issue is also fixed by @Consolatis's patch :) Thanks a lot!

I assume only on 0.7.1 though, the text background rect should not be solved by the pre-multiplied fix.

**Comment by johanmalm** [comment]
I think we should consider generating the whole titlebar as once piece.

We've discussed this before in the context of supporting non-vertical gradients, but I suspect it would help with the transparent surface on top of another transparent surface problem too.

This potential disadvantages are:
- A more expensive operation during resizing, but we may well find it's negligible compared with what the client has to do anyway.
- More SSD buffers have to be window specific.

Considerations:
- Should buttons be transparent/opaque (including hover/press/etc buttons).
- If we went down the monolithic path, should buttons be part of titlebar mega-buffer? (I think not).

**Comment by ahesford** [comment]
Even if we have to disable sub-pixel rendering for transparent windows, I definitely agree that it should remain enabled for fully opaque windows, because it definitely looks better.

However, if we can draw the title bar monolithically and just do the right thing always, that's preferable. It might be nice to completely rethink button handling and integrate the corner radius (with scaling!) into the title bar, but I haven't looked at button handling and don't have any proposals for how to do things properly.

**Comment by jlindgren90** [comment]
A monolithic (single buffer) titlebar would definitely solve some issues. I like that idea at least long-term. 
I think subpixel rendering would still need to be disabled even then, unless fully opaque.

I think we could still do a smaller fix for the specific translucency issue in the short-term.

**Comment by jlindgren90** [comment]
Off-topic: I've wondered if labwc could have a "low-resource" mode for lower-end/older systems (e.g. without HW shaders) and in that configuration use plain RGB buffers, only rectangular corners, etc. and avoid the need for RGBA blending in most cases.

**Comment by Consolatis** [comment]
Leaving this open to track the title background issue on translucent titlebar.

**Comment by jlindgren90** [comment]
Corner buttons also do not match the rest of the titlebar exactly for me, even after #1685. It is most noticeable over a dark background.

```
window.active.title.bg.color: #134a8c 60
window.inactive.title.bg.color: #323232 60
```

![Screenshot 2024-04-07 00:52:05](https://github.com/labwc/labwc/assets/1244737/3c99a595-fd16-4829-8fa7-e0a17a0995a4)

**Comment by jlindgren90** [comment]
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4635 fixes the corner button issue with the vulkan renderer (actually the corner buttons are correct, the color conversion is wrong for the rest of the titlebar).

**Comment by Consolatis** [comment]
The title on translucent titlebar issue should be solved on latest master by #1688.
Thanks again for the reports, I'll close this issue but feel free to comment / reopen if something still isn't right.
