### ISSUE TITLE
Window menu fails to appear at top-left corner after right-clicking titlebar in maximized state

### ISSUE THREAD

**Issue by st0rm-shad0w** [labwc/labwc#2404]
### Problem description

**Description:** There is a bug with the window menu in the maximized state. After right-clicking on the titlebar, the menu appears at the location of the right-click instead of the top-left corner. If you then click the dedicated menu button, the menu continues to appear at the right-click position. This does not happen in the normal (non-maximized) state.

https://github.com/user-attachments/assets/57e8c15d-934f-4081-8c2c-a6ac3f96bf56

### Steps to reproduce

**Steps to Reproduce:**

1. Maximize a window.
2. Right-click on the titlebar.
3. Observe that the window menu appears at the right-click position.
4. Click the dedicated menu button.
5. Observe that the window menu appears at the right-click position instead of the top-left corner.

### labwc build source

Local build

### labwc version

labwc 0.8.1-115-g2ade6a1e-dirty

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Void Linux

**Comment by Consolatis** [comment]
Thanks for the report. IMHO we should fix that before 0.8.2. I can take a look after the WE but if somebody else feels like looking into it feel free.

**Comment by johanmalm** [comment]
I can't reproduce this. Have had a quick look at code, and it's not clear to me what might cause this.

Suggest the following:

1. Delete your local build directory and re-compile. Confirm issue still exists with a clean build.
2. Run with default configuration (`labwc -C /dev/null`). Confirm issue still exists.
3. Do some detective work by inserting some `wlr_log()` in `show_menu()` and post output here. Suggest starting with the patch below.

```C
diff --git a/src/action.c b/src/action.c
index 195a9171..2d63229f 100644
--- a/src/action.c
+++ b/src/action.c
@@ -663,6 +663,9 @@ show_menu(struct server *server, struct view *view, struct cursor_context *ctx,
 	int x = server->seat.cursor->x;
 	int y = server->seat.cursor->y;
 
+	wlr_log(WLR_ERROR, "x=%d; y=%d; at_cursor=%d; pos_x=%s; pos_y=%s; view=%p",
+		x, y, at_cursor, pos_x, pos_y, view);
+
 	/* The client menu needs an active client */
 	bool is_client_menu = !strcasecmp(menu_name, "client-menu");
 	if (is_client_menu && !view) {
```

**Comment by st0rm-shad0w** [comment]
Thanks for the quick reply @johanmalm! 

For me the issue still persists even after trying trying *1 and *2. Attached a video of my attempt, please do check and let me know if something is amiss.

https://github.com/user-attachments/assets/3bfdb0ee-cdad-45d4-a1b4-4efa735572ea

Also, launching by compiling the patch in *3, generates the following messages. I attempted right click followed by menu button click three times.

```
❯ build/labwc -C /dev/null -s foot
00:00:00.049 [sfdo-desktop] 15:72: Syntax error
00:00:00.049 [sfdo-desktop] Failed to load /usr/share/applications/pcmanfm-qt-desktop-pref.desktop
00:00:00.074 [sfdo-desktop] 82:71: Syntax error
00:00:00.074 [sfdo-desktop] Failed to load /usr/share/applications/lxqt-config-file-associations.desktop
00:00:00.149 [sfdo-desktop] 67:81: Syntax error
00:00:00.149 [sfdo-desktop] Failed to load /usr/share/applications/lxqt-config-input.desktop
00:00:00.160 [sfdo-desktop] 1:1: Exec is unset while DBusActivatable is unset or false
00:00:00.160 [sfdo-desktop] Failed to load /usr/share/applications/qemu.desktop
warn: wayland.c:1619: compositor does not implement the XDG toplevel icon protocol
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
Errors from xkbcomp are not fatal to the X server
00:00:09.841 [../src/action.c:666] x=883; y=6; at_cursor=1; pos_x=(null); pos_y=(null); view=0x5599f8de70
00:00:11.433 [../src/action.c:666] x=1; y=18; at_cursor=0; pos_x=(null); pos_y=(null); view=0x5599f8de70
00:00:11.433 [../src/menu/menu.c:875] Failed to position menu client-menu () and its submenus: Not enough screen space
00:00:13.237 [../src/action.c:666] x=2275; y=9; at_cursor=1; pos_x=(null); pos_y=(null); view=0x5599f8de70
00:00:15.847 [../src/action.c:666] x=9; y=9; at_cursor=0; pos_x=(null); pos_y=(null); view=0x5599f8de70
00:00:15.847 [../src/menu/menu.c:875] Failed to position menu client-menu () and its submenus: Not enough screen space
00:00:16.907 [../src/action.c:666] x=102; y=11; at_cursor=1; pos_x=(null); pos_y=(null); view=0x5599f8de70
00:00:18.603 [../src/action.c:666] x=13; y=15; at_cursor=0; pos_x=(null); pos_y=(null); view=0x5599f8de70
00:00:18.604 [../src/menu/menu.c:875] Failed to position menu client-menu () and its submenus: Not enough screen space
```

**Comment by tokyo4j** [comment]
Oh, it looks like a regression from #2403. With that PR, negative `x` values can be passed to `menu_open_root()`, which fails to position the menu with negative `x`. You saved us from introducing a regression. We'll definitely need to fix this.

**Comment by tokyo4j** [comment]
This issue is fixed by the revert in #2407. And the fix for menu alignment (#2403), which caused this issue, is reapplied with #2442.
