### ISSUE TITLE
issues with application icon scaling after #2444

### ISSUE THREAD

**Issue by Flrian** [labwc/labwc#2450]
### Problem description

I've noticed that the way most of my application icons in the titlebar are smaller and some even get cut off after #2444.

As you can see in the screenshot, in the nested labwc instance running with the commit prior to the pr foot has a bigger application icon, while in the main instance it is smaller and the discord/vscode icons just get cut off. 

![2024-12-24T02:16:11](https://github.com/user-attachments/assets/f108a03a-282b-4414-8dbe-c6f0c789563c)

### Steps to reproduce

Might have something to do with the combination of window button height and titlebar padding in my theme?
```
window.button.height: 16
window.titlebar.padding.height: 8
window.titlebar.padding.width: 4
```

### labwc build source

Local build

### labwc version

16dbdc64e58d66011bbf319b92de844dab0ca8d9

### labwc environment

From a TTY or some display manager like lightdm

**Comment by tokyo4j** [comment]
The cut-off icons should be fixed by #2451, but let me think about the problem of smaller icons for a while. Perhaps we should go back to the previous behavior that the padding of `window.button.width / 10` was applied only horizontally for window icons.

**Comment by johanmalm** [comment]
Should be fixed with #2451.

**Comment by tokyo4j** [comment]
The problem of smaller icon is not resolved yet.

Before #2444, the padding around icon with the size of (button size) / 10 is applied only horizontally, but #2444 changed it to apply in both directions as I felt it's more natural.

But I think we should at least provide a way for @Flrian to restore the original icon size. We can:
1. Make the padding configurable via `window.icon.padding` with default size of 2px
2. Or add a more sophisticated heuristic to determine the padding size based on `window.titlebar.padding.width`, `window.titlebar.padding.height` and `window.button.spacing`.
3. Or rollback to the original behavior that applies the padding only horizontally.

I've made a patch for (2.) like below:

<details><summary>patch</summary>

```diff
diff --git a/src/ssd/ssd-titlebar.c b/src/ssd/ssd-titlebar.c
index 9c24b431..ed58918f 100644
--- a/src/ssd/ssd-titlebar.c
+++ b/src/ssd/ssd-titlebar.c
@@ -569,6 +569,41 @@ ssd_should_be_squared(struct ssd *ssd)
 		&& view->maximized != VIEW_AXIS_BOTH;
 }
 
+static int
+get_icon_padding(struct theme *theme)
+{
+	/*
+	 * First, get the space around the icon inside the button if no icon
+	 * padding were applied (thus either of icon_space_{x,y} is zero).
+	 */
+	int max_icon_size = MIN(theme->window_button_width,
+				theme->window_button_height);
+	int icon_space_x = (theme->window_button_width - max_icon_size) / 2;
+	int icon_space_y = (theme->window_button_height - max_icon_size) / 2;
+	/*
+	 * Next, get the spaces from the button to the titlebar edges and the
+	 * adjacent buttons.
+	 */
+	int button_space_x_edge = theme->window_titlebar_padding_width;
+	int button_space_y_edge =
+		(theme->titlebar_height - theme->window_titlebar_padding_width) / 2;
+	int button_space_x_adjacent_button = theme->window_button_spacing;
+	/*
+	 * Then get the minimum space from the icon to the titlebar edges and
+	 * the adjacent buttons if no icon padding were applied.
+	 */
+	int minimum_space =
+		MIN(button_space_x_edge + icon_space_x,
+			MIN(button_space_y_edge + icon_space_y,
+				button_space_x_adjacent_button + icon_space_x));
+	/*
+	 * Finally return the actual icon padding size inside the button, which
+	 * makes sure there's a space of at least 1/10 of the button size
+	 * around the icon.
+	 */
+	return MAX(0, max_icon_size / 10 - minimum_space);
+}
+
 void
 ssd_update_window_icon(struct ssd *ssd)
 {
@@ -590,15 +625,7 @@ ssd_update_window_icon(struct ssd *ssd)
 
 	struct theme *theme = ssd->view->server->theme;
 
-	/*
-	 * Ensure a small amount of horizontal padding within the button
-	 * area (2px on each side with the default 26px button width).
-	 * A new theme setting could be added to configure this. Using
-	 * an existing setting (padding.width or window.button.spacing)
-	 * was considered, but these settings have distinct purposes
-	 * already and are zero by default.
-	 */
-	int icon_padding = theme->window_button_width / 10;
+	int icon_padding = get_icon_padding(theme);
 	int icon_size = MIN(theme->window_button_width - 2 * icon_padding,
 		theme->window_button_height - 2 * icon_padding);
```

</details>

... but it seems a bit too complicated. So I prefer (1.).

@jlindgren90 Any thoughts?

**Comment by johanmalm** [comment]
I like (1) too. 

Or we could consider a `window.icon.size` option.

That would increase the chances of users getting it right and rendering icons in their original size - and basically just cap the size at `window.button.{width,height}`

**Comment by johanmalm** [comment]
> Can we keep this issue open for now and wait for further feedback from other users, given that @Flrian fixed the issue of small icons by himself? Adding a new theme configuration is easy, but I'm afraid it doesn't fit what users actually need despite the need to maintain backward compatibility...

Agree. It's much better to think it through thoroughly before committing :smile:

**Comment by orfeasxyz** [comment]
> Or add a more sophisticated heuristic to determine the padding size based on window.titlebar.padding.width, window.titlebar.padding.height and window.button.spacing.

I like the idea of having padding and spacing as two separate options so I would root for that.

**Comment by tokyo4j** [comment]
I decided to take the third option in https://github.com/labwc/labwc/issues/2450#issuecomment-2564633383 for now as a quick fix, as I observed at least two people in this thread having trouble with the change about the icon padding in #2444.
