### ISSUE TITLE
Switch to window after iconifying it does non display it

### ISSUE THREAD

**Issue by gtellalov** [labwc/labwc#2582]
### Problem description

When iconifying a maximised window it can no longer be displayed even though when switching to it, it gets focused.

### Steps to reproduce

1. Maximise a window
2. Iconify it
3. Switch to it with NextWindow or PreviousWindow

### labwc build source

Local build

### labwc version

labwc 0.8.2-125-ga4d1fcfe

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Arch Linux

**Comment by johanmalm** [comment]
Works fine here. What application does it happen with?

**Comment by domo141** [comment]
hmm, happens to me too

2 urxvt windows, one maximized, then that iconofied - alt-tab shows it, but after releasing, that maximized window disappears..

**Comment by domo141** [comment]
eventually I got that one back to view with sfwbar...

**Comment by tokyo4j** [comment]
I can't reproduce it... Does it happen when you start labwc with the default config like `labwc -C /tmp -s urxvt`? Also, did you maximize/iconify the window with the titlebar buttons?

**Comment by gtellalov** [comment]
No, it doesn't happen with the default config. My config has titlebar disabled, but I could reproduce it both form a keyboard shortcut and the window menu (ShowMenu). 
Here's my config in case it helps reproduce it: http://0x0.st/8NIw.xml

**Comment by domo141** [comment]
actually, in my case, the window does not need to be maximized... i'll explore more

**Comment by domo141** [comment]
now I have 2 "normal" urxvt windows, both minimized, neither gets back. I had to skip the view first
time in the "switcher" alt-tab popped up (i.e. choose other view). If I chose the latest minimized view
immediately in the window switcher then the view came back to be useable. Keyboard focus were given
to the view that is invisible, though (I have focus-follow mouse, but mouse not over any of the othet views...)

**Comment by domo141** [comment]
```
   <keybind key="A-Tab">
      <action name="NextWindow" />
    </keybind>
```

**Comment by domo141** [comment]
I can reproduce in nested labwc. there I also tried w/ fedora-41 -shipped labwc 0.8.2 (where deiconifying works)
In 0.8.2 windowSwitcher shows small 'm' for minimized views -- latest github master the space is empty (i.e. no 'm')

**Comment by tokyo4j** [comment]
> now I have 2 "normal" urxvt windows, both minimized, neither gets back. I had to skip the view first time in the "switcher" alt-tab popped up (i.e. choose other view). If I chose the latest minimized view immediately in the window switcher then the view came back to be useable. Keyboard focus were given to the view that is invisible, though (I have focus-follow mouse, but mouse not over any of the othet views...)

I don't understand what's happening... Does it happen with the default configuration (`labwc -C /tmp -s urxvt`)?

Also, I will appreciate it if you provide a demo video showing the issue.

**Comment by domo141** [comment]
Just tried in nested `labwc with -C /tmp` -- and there deiconifying works OK. I keep experimenting
(and will make demo in that nested labwc after a while...)

**Comment by domo141** [comment]
[uu.txt](https://github.com/user-attachments/files/18815784/uu.txt)

Haha, the attachment is .mkv -- for some reason file uploaded did not show it
(and neither did .zstd-"compressed") one.

whatever the reason is I don't know (formula too complex?) anyway that video
shows the same pattern: views change order in window switcher and at the same
time the 'm' (or ... if m cannot be shown) disappears (and then view is un-focusable
(except via some foreign-toplevel usage)

**Comment by domo141** [comment]
more:

`wlrctl toplevel find 'state:minimized'` did not find anything, returned nonzero

started new urxvt, minimized it and then the above wlrctl command returned zero. carefully unmaximized and closed the view from the system.

then learned a bit more of wlrcrl (in addition to the above)

`wlrctl toplevel find 'title:too @yks 11 (21860)'` found my view that was un"iconifiable"

`wlrctl toplevel focus 'title:too @yks 11 (21860)'` gave focus to it (still not visible but known from previous trials)

`wlrctl toplevel maximize 'title:too @yks 11 (21860)'` maximized it, just that still not visible ('M' in windowSwitcher, was shown, but when chosen in that switcher, but disappeared after releasing keys.

... and now I got an idea... after


`wlrctl toplevel minimize 'title:too @yks 11 (21860)'`

ALT+TAB (still) showed the view with 'M', but now, when selected, it did not disappear anymore.
my guess is that now it has "minimized" status and therefore it could be "unminimized".

**Comment by tokyo4j** [comment]
Well, I just want to reproduce the issue. Then I can inspect the internal state with gdb.

Could you provide rc.xml and minimum procedure to reproduce the issue?

**Comment by domo141** [comment]
I took the docs/rc.xml from labwc repo, and added

```
  <focus>
    <followMouse>yes</followMouse>
    <followMouseRequiresMovement>no</followMouseRequiresMovement>
    <raiseOnFocus>no</raiseOnFocus>
  </focus>

 <windowSwitcher show="yes" preview="yes" outlines="yes" allworkspaces="no">
    <fields>
      <field content="type_short" width="8%" />
      <field content="state" width="8%" />
      <field content="trimmed_identifier" width="15%" />
      <field content="title" width="69%" />
    </fields>
  </windowSwitcher>
```
(focus made difference, windowSwitcher to show 'm's) and then run:
```
path/to/labwc -C /tmp/ -s 'urxvt -fn xft:Monospace-12' -c path/to/rc.xml
```

In that first urxvt window I started 2 more with `urxvt &`, then minimized all three
and then uset ALT+TAB to cycle through the views -- usually when the cycle started
from the first one the 'm' disappeared and then the view was un-minimizable...

the view can be unminimized from e.g. sfwbar (by clicking 3 times  - i think it first focuses,
second minimizes and 3rd focuses again, as...) or with wrlctl by first minimize and then focus.

**Comment by tokyo4j** [comment]
Thanks. I spotted the issue and made a fix for it.

**Comment by gtellalov** [comment]
I didn't test #2584, but this one is still present. When iconifying a maximised window it fails to be displayed again.
This time the non-maximised windows are displaying properly, but a maximised window is not.

**Comment by domo141** [comment]
i could reproduce. I downloaded that  http://0x0.st/8NIw.xml mentioned earlier and then:

`path/to/labwc -C /tmp/ -c path/to/8NIw.xml -s foot`

there I started second `foot` from command line ... and then some less(1)ing for keybinds...

`W-m` maximizes `W-n` minimizes and `W-t` nextwindows (and focuses!)

so, first W-m, then W-n -- and after that the maximized window in no-longer unminimizable
(except it once happened in my vigorous trying but haven't been able to do again...)

**Comment by tokyo4j** [comment]
The issue fixed by the PR is different from the original issue I explained in https://github.com/labwc/labwc/issues/2582#issuecomment-2661504284.

If the issue only happens with the NextWindow & Focus combination, it should be addressed in the next release cycle, as focus management is complex and I don't want to touch the code now. However, please report if you think this is a regression that didn't exist in 0.8.2.

**Comment by gtellalov** [comment]
It is not a regression. The problem is present in 0.8.2 as well.

**Comment by tokyo4j** [comment]
> Edit: To add, the problem doesn't seem to be with the focus, because when switched to the minimised window, even though it's not displayed it received key strokes. For example a terminal that's not displayed will terminate with Ctrl+D.

I believe the problem is related to focus. The cause is, `Focus` action calls `desktop_focus_view()` which focuses, un-minimizes and raises a window, even while window switching.

#2588 should fix it. Could you test it?

**Comment by gtellalov** [comment]
I have tested it with your fork and the problem is still there, but I noticed that the version of the said fork is labwc 0.7.0-917-g6927153a.

- The issue happens with both NextWindow and PreviousWindow (and Focus). If running under xfce the window can be shown by clicking on the panel button (the taskbar), but when running bare labwc there is no way to display the window.
- Actually the issue happens without maximising the window as well.

**Comment by domo141** [comment]
I tried again, not (yet, if ever) picked tokyo's change (as I was reproducing the problem first...)

First I had hard time not failing to get the windows back, but then I could have the problem
with both maximized, then minimized, and with windows that I did not maximize...

Then I realized I may be able to do "middle-ground" testing by outcommenting the 
 `<action name="Focus"/>` part and reconfiguring. I did that for the `W-t` (nextwindow) binding
but not for `W-h` (previouswindow) binding. I could not get the minimized windows back
(but I maybe did not try hard enough)...

as I restarted. Now I am not quite sure whether I ever got the windows unminimizing problem
appear when I used the `W-t` binding, and I do get with `W-h` but cannot say exactly when...

And when the unminize problem was active, neither `W-t` not `W-h` binding could unminimize.

But when focus was given to a window and then it got back hidden if I pressed `W-n` (the minimize 
toggle) and now `W-t` the window appeared and stayed visible. With `W-h` the window got hidden
again. (and the difference was that W-h still had that focus action configured).

I now apply the related commit that is supposed to be fixing the issue - let's see how playing
it with goes...

**Comment by domo141** [comment]
Ok, With the related commit applied I could not reproduce the issue (tried somewhat hard...).

To know more I added the `<field content="state" width="3%" />` and now I saw the 'm' was kept
there until I chose that particular window to bring it back...

... so i went back running that labwc w/o this commit applied

and there, quite soon I got to the situation that the 'm' disappeared before I tried to bring
such a windows back (just kept pressing `W-h` enough times and all 'm's disappeared).
If I pressed `W-n` then 'm' reappeared in windowSwitcer but using `W-h` could not be used
to bring the window back. `W-t` (the binding w/o action focus) then brought those back.

I tried with both of these labwc builds second time, with same results, a bit of scientific
methods there ;)

**Comment by tokyo4j** [comment]
> I have tested it with your fork and the problem is still there, but I noticed that the version of the said fork is labwc 0.7.0-917-g6927153a.

That's strange. I guess you didn't successfully build [my fork](https://github.com/tokyo4j/labwc/tree/fix/focus-action-while-window-switching).

> - The issue happens with both NextWindow and PreviousWindow (and Focus). If running under xfce the window can be shown by clicking on the panel button (the taskbar), but when running bare labwc there is no way to display the window.

Sorry, I think my English was bad. My assumption is:
- The issue happens with `<action name="NextWindow" /><action name="Focus" />` keybind
- But the issue doesn't happen with `<action name="NextWindow" />` keybind only

Is my assumption correct?

> - Actually the issue happens without maximising the window as well.

OK. That matches what I could reproduce.

@domo141 Thank you for investigation. I think your result matches my assumption that the issue only happens with the combination of `NextWindow` (or `PreviousWindow`) and `Focus` actions.

**Comment by gtellalov** [comment]
> That's strange. I guess you didn't successfully build [my fork](https://github.com/tokyo4j/labwc/tree/fix/focus-action-while-window-switching).

You're right. I haven't checked out the correct branch.

I tested again and the issue is fixed. Minimised windows are getting back with NextWindow and Focus.

I also tested the latest labwc and the problem isn't there without the Focus action, i.e. only NextWindow displays the window properly.

**Comment by johanmalm** [comment]
It is not clear to me what is going on in this issue.

Unless I'm missing something I don't think the combination of `NextWindow` and `Focus` is valid. Just because we have exposed the ability to define mouse/key-binds to such a fine-grained extent does not mean that all combinations make sense. I feel that this is such a case.

I suggest that we close this issue and if there is a problem with anything other than the NextWindow-Focus thing, then raise that on top of #2584 and make clear what follow-mouse options are being used.

I know it's sometimes hard, but please try to stick to one bug per issue.
