### ISSUE TITLE
Be more resilient on output failure

### ISSUE THREAD

**Issue by FederAndInk** [labwc/labwc#2697]
### Problem description

When on a TTY for some time (~20min to ~3 hours) and switching back to the graphical session the output is frozen, I get the following logs:

```log
avril 25 09:03:00 CP1 labwc[2243]: 18:15:54.072 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
avril 25 09:03:00 CP1 labwc[2243]: 18:15:54.080 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
avril 25 09:03:00 CP1 labwc[2243]: 18:15:54.089 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
avril 25 09:03:00 CP1 labwc[2243]: 18:15:54.432 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
avril 25 09:03:01 CP1 labwc[2243]: 18:15:54.863 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
avril 25 09:03:01 CP1 labwc[2243]: 18:15:55.247 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
avril 25 09:03:02 CP1 labwc[2243]: 18:15:55.862 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
avril 25 09:03:02 CP1 labwc[2243]: 18:15:56.031 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
avril 25 09:03:03 CP1 labwc[2243]: 18:15:56.830 [ERROR] [/usr/src/debug/wlroots-0.18/0.18.2/types/output/output.c:721] Basic output test failed for DP-1
```

I can still switch to a TTY again and no freeze there, If a do a `sleep 2 && wlr-randr --output DP-1 --preferred` then go to the graphical session it gets unstuck and no more errors in the logs.

The switch back to the graphical session is not the cause, as the log appears way before the switch when I'm still on the TTY.

I also have tried to monitor with udev if there were any changes/events and there wasn't unfortunately.

I might also have a bad environment (screen and/or cable and/or power issue) causing this, as the issue appears randomly. Unfortunately, I cannot change this as I am not in charge of it, and haven't been able to identify the root cause.

I will try to launch labwc in debug mode and try to reproduce the issue.

This problem might probably be generalized and might also appear on the graphical session directly.
I think it should be preferable to detect/catch the error and try to "reload" the output, I've seen that the functions called return a `bool` (`output_basic_test`, `output_prepare_commit`, `wlr_output_commit_state`, ...)

If I have the time I might try to see if I can make a patch and contribute it, if you could point me to some resources and places to start looking (e.g. 
- where are the outputs handled in labwc
- what could I do to "reload" the output programmatically with wlroot/labwc?
- if something like an output manager might do a better job at maintaining the output in a correct state over time, like kanshi?
).

Informations:
- build with yocto scarthgap, using this recipe&version (0.8.3 + wlroot 0.18.2 + libdrm 2.4.124): https://codeberg.org/flk/meta-wayland/src/commit/9a9fa8e1aac7418a8a941d33ec00b595b2f6a007/recipes-wlroots/labwc/labwc_git.bb
- kernel mainline yocto 6.6.69
- labwc is launched with a systemd service (with its own session+pam), similar to this one made for weston: https://git.openembedded.org/openembedded-core/tree/meta/recipes-graphics/wayland/weston-init/weston.service?id=54c84be6e4643396b47b7d8cca803f914455ade9

Many thanks, and btw labwc is really great 👍

### Steps to reproduce

Unfortunately, I don't have precise step-by-step instructions to reproduce this, but I guess the output can be made to fail either programmatically through drm/kernel commands or by parasiting the output/cable/power with some kind of electromagnetic testing?

### labwc build source

Local build

### labwc version

0.8.3

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Yocto Scartgap

**Comment by FederAndInk** [comment]
I am also using `wlopm` to blank the screen after 10 minutes (although the errors are not correlated with the timeout of swayidle):

```bash
swayidle -w \
  timeout 600 'wlopm --off \*' \
  resume 'wlopm --on \*' &
```

**Comment by cunlem** [comment]
Hey I'm also suffering from this bug when switching between labwc (0.8.4) sessions on different VTs. Thanks for the tip on how to unfreeze the output!

> I might also have a bad environment (screen and/or cable and/or power issue) causing this, as the issue appears randomly.

Happens to me with laptop's internal display (`LVDS-1`)

Edit: I'm testing 0.9.1 now

**Comment by cunlem** [comment]
Unfortunately this happens all the time with current labwc and wlroots 0.19.1

```
01:50:13.601 [INFO] [backend/drm/backend.c:112] DRM FD paused
01:50:13.602 [ERROR] [../src/view.c:898] view has no output, not positioning
01:50:13.602 [ERROR] [backend/drm/drm.c:1349] connector DP-1: Failed to disable CRTC 47
```

```
01:50:36.722 [INFO] [backend/drm/backend.c:112] DRM FD resumed
01:50:36.856 [INFO] [backend/drm/drm.c:1855] connector LVDS-1: Requesting modeset
01:50:36.856 [ERROR] [../src/output.c:842] failed to get output layout box
01:50:36.856 [ERROR] [../src/view.c:898] view has no output, not positioning
01:50:36.856 [INFO] [backend/drm/drm.c:1855] connector DP-1: Requesting modeset
01:50:36.856 [ERROR] [../src/output.c:842] failed to get output layout box
01:50:36.856 [ERROR] [../src/output.c:842] failed to get output layout box
01:50:36.857 [ERROR] [../src/view.c:898] view has no output, not positioning
01:50:36.905 [ERROR] [types/output/swapchain.c:109] Swapchain for output 'DP-1' failed
```

This is with `autoEnableOutputs` disabled using kanshi for output management which I think is the reason `Basic output test failed` line does not appear.

Is this reproducible across the board?

**Comment by cunlem** [comment]
I haven't experienced this bug in a long time I suppose it may have been fixed by wlroots 0.19.2 point release

**Comment by johanmalm** [comment]
@FederAndInk Would you be able to confirm the status from your end? Are you on wlroots `0.19.2`?

**Comment by SjoerdV** [comment]
using labwc `0.20.1` with wlroots `0.20.1` using the vulkan renderer and HDR enabled (cool!) this is still happening on resume from suspend (S3) quite often. Certainly some kind of race because it's not *always* reporting `Failed to disable CRTC <xx>` followed by seatd crashing and returning to the greeter. Issue started after the 0.18 versions (so starting with 0.19) is my experience.

relevant log:
```
Jun 20 00:39:52 mymachine seatd[1994]: 06:45:41.411 [INFO] [seatd/seat.c:621] Disabling client 7 on seat0
=== SUSPEND HAS NOW COMPLETED
=== RESUME IS STARTING
Jun 20 02:06:44 mymachine seatd[1994]: 06:45:55.784 [ERROR] [seatd/seat.c:334] Could not open device: client is not active
Jun 20 02:06:44 mymachine seatd[1994]: 06:45:55.784 [ERROR] [seatd/client.c:229] Could not open device: Operation not permitted
Jun 20 02:06:44 mymachine labwc[2942]: 06:45:47.693 [ERROR] [backend/session/session.c:340] Failed to open device: '/dev/input/event24': Operation not permitted
Jun 20 02:06:45 mymachine labwc[2942]: 06:45:48.013 [ERROR] [backend/drm/drm.c:1385] connector DP-3: Failed to disable CRTC 82
Jun 20 02:06:45 mymachine seatd[1994]: 06:45:56.104 [INFO] [seatd/seat.c:640] Disabled client 7 on seat0
Jun 20 02:06:45 mymachine seatd[1994]: 06:45:56.104 [INFO] [seatd/seat.c:584] Opened client 7 on seat0
Jun 20 02:06:45 mymachine labwc[2942]: labwc: types/output/output.c:401: wlr_output_finish: Assertion `wl_list_empty(&output->events.bind.listener_list)' failed.
Jun 20 02:06:45 mymachine labwc[4239]: (EE) failed to read Wayland events: Broken pipe
Jun 20 02:06:46 mymachine seatd[1994]: 06:45:56.948 [INFO] [seatd/client.c:480] Client disconnected
Jun 20 02:06:46 mymachine seatd[1994]: 06:45:57.704 [INFO] [seatd/seat.c:158] No clients on seat0 to activate
Jun 20 02:06:46 mymachine seatd[1994]: 06:45:57.704 [INFO] [seatd/seat.c:297] Removed client 7 from seat0
Jun 20 02:12:00 mymachine seatd[1994]: 06:51:11.668 [INFO] [seatd/seat.c:158] No clients on seat0 to activate
Jun 20 02:12:08 mymachine seatd[1994]: 06:51:19.747 [INFO] [seatd/seatd.c:218] seatd stopped
Jun 20 02:12:16 mymachine seatd[367867]: 00:00:00.000 [INFO] [seatd/seat.c:48] Created VT-bound seat seat0
Jun 20 02:12:16 mymachine seatd[367867]: 00:00:00.000 [INFO] [seatd/seatd.c:194] seatd started
=== GREETER IS DISPLAYED AFTER RESUME SUCCEEDED, BUT FAILED TO ACTUALLY RESUME THE ACTIVE SESSION
```

NOTE: The `/dev/input/event24` message is a disabled synaptics touchpad, not important...
