### ISSUE TITLE
Cannot scroll with labwc

### ISSUE THREAD

**Issue by Parmjot-Singh** [labwc/labwc#274]
I have no idea if this is just me being dumb, or if this is a genuine issue, but I cannot scroll with my mouse, and my touchpad. Searching anywhere doesn't lead to much though.

**Comment by Consolatis** [comment]
What version / branch of labwc are you using?

**Comment by Parmjot-Singh** [comment]
The latest version. 0.5.0-1, from the AUR.

**Comment by Consolatis** [comment]
There are some bugfixes in branch v0.5 but we haven't done a minor release for those yet.
One of them was indeed a fix for touchpad scrolling, does it work if you start an application, don't touch the touchpad and just scroll with the mouse?

**Comment by Parmjot-Singh** [comment]
Should I downgrade to branch v0.5?
I'll try to do it with my current install

**Comment by Parmjot-Singh** [comment]
Nope, doesn't work.

**Comment by Parmjot-Singh** [comment]
Downgrading to that branch doesn't work.

**Comment by Parmjot-Singh** [comment]
Ok, so scrolling doesn't work in my web browser, but it works in my terminal.

**Comment by Consolatis** [comment]
> Downgrading to that branch doesn't work.
So you where able to compile and use the branch but scrolling still doesn't work?

> Ok, so scrolling doesn't work in my web browser, but it works in my terminal.
If you `A-Tab` what does it say in front of your terminal and web browser? `[xdg-shell]` or `[xwayland]`?

**Comment by Parmjot-Singh** [comment]
It says [xwayland]
It does have the ability to run natively as wayland though, as it uses electron (Min)
I'll see if this is a issue only this browser, by checking other browsers.

**Comment by johanmalm** [comment]
@Parmjot-Singh 

Could you try with the latest commit on the `v0.5 branch`

```
git clone https://github.com/labwc/labwc.git
cd labwc
git checkout v0.5
meson build
ninja -C build/
./build/labwc
```

**Comment by Parmjot-Singh** [comment]
I will, once I get my laptop back, because the hinge for the screen broke.

**Comment by johanmalm** [comment]
Believed fixed by https://github.com/labwc/labwc/commit/ce38d2dbd6cff723bca12bb423a569bae8354bfb
Shout if not.

**Comment by Parmjot-Singh** [comment]
@johanmalm I cloned the latest repo, built and installed it, and still have the same issue.

**Comment by johanmalm** [comment]
> git clone https://github.com/labwc/labwc.git
> cd labwc
> git checkout v0.5
> meson build
> ninja -C build/
> ./build/labwc

Did you take these exact steps?

**Comment by Parmjot-Singh** [comment]
I forgot to do the checkout part. It works now. Thanks

**Comment by acoolstraw** [comment]
also had that issue, appeared to happen only on Electron but not on plain Chromium

**Comment by johanmalm** [comment]
@acoolstraw is it fixed now?
If not, let us know if it’s with 0.5.1 or master

**Comment by acoolstraw** [comment]
can confirm scrolling works on 0.5.1
