### ISSUE TITLE
sendEventsMode="disabledOnExternalMouse" rejected as non-boolean

### ISSUE THREAD

**Issue by ManuLinares** [labwc/labwc#3293]
### Problem description

labwc rejects valid libinput values for <sendEventsMode> when parsing XML device configuration.
Using sendEventsMode="disabledOnExternalMouse" results in the error:
```
[ERROR] [../labwc/src/common/parse-bool.c:29] (disabledOnExternalMouse) is not a boolean value
```

According to this: https://labwc.github.io/labwc-config.5.html#entry_libinput_device_sendeventsmode it should disable my ps2 mouse if my wireless mouse is connected.

### Steps to reproduce

1. My rc.xml:

```xml
...
  <libinput>
    <device category="Logitech USB-PS/2 Optical Mouse">
      <pointerSpeed>0.0</pointerSpeed>
      <accelProfile>adaptive</accelProfile>
      <sendEventsMode>disabledOnExternalMouse</sendEventsMode>
    </device>
  
    <device category="Logitech Wireless Mouse">
      <pointerSpeed>-0.8</pointerSpeed>
      <accelProfile>adaptive</accelProfile>
      <scrollFactor>1.0</scrollFactor>
    </device>
  </libinput>
...
```

2. restart labwc

### labwc build source

Local build

### labwc version

0.9.2.r112.gfd6d62ea-1

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Archlinux

**Comment by Consolatis** [comment]
I think this is just a slightly annoying misleading log message. Looking at `get_send_events_mode()`, `disabledOnExternalMouse` should indeed work, regardless of the error log.

**Comment by Consolatis** [comment]
Should be fixed by #3294, testing appreciated.

**Comment by ManuLinares** [comment]
Hi, thanks for the fix but this fixes only the error log.

My issue still persists. According to this: https://labwc.github.io/labwc-config.5.html#entry_libinput_device_sendeventsmode it should disable my ps2 mouse if my wireless mouse is connected with a config like this one:

```xml
	<libinput>
		<device category="Logitech USB-PS/2 Optical Mouse">
			<pointerSpeed>0.0</pointerSpeed>
			<accelProfile>adaptive</accelProfile>
			<sendEventsMode>disabledOnExternalMouse</sendEventsMode>
		</device>
	
		<device category="Logitech Wireless Mouse">
			<pointerSpeed>-0.8</pointerSpeed>
			<accelProfile>adaptive</accelProfile>
			<scrollFactor>1.0</scrollFactor>
		</device>
	</libinput>
```

```bash
 $ libinput list-devices | grep Device
Device:                  Logitech USB-PS/2 Optical Mouse
Device:                  Logitech Wireless Mouse
```

**Comment by Consolatis** [comment]
The functionality is designed for touchpads in laptops. I don't know if libinput supports this for an external mouse. I would expect it doesn't because it would always disable the device because it is itself an external mouse.

**Comment by ManuLinares** [comment]
Thanks Consolatis, as discussed in the iirc this is not supported by libinput.

libinput decides what is an external/internal device and this option only works for the internal ones.
